### ISSUE TITLE
这个lab的高度问题

### ISSUE THREAD

**Issue by yinxianwei** [xhzengAIB/iOS8SelfSizingCells#4]
首次启动是这样的：
[图一](http://7teblm.com1.z0.glb.clouddn.com/QQ20150415-1@2x.png)

![](http://7teblm.com1.z0.glb.clouddn.com/QQ20150415-1@2x.png)

然后我滑动tabview就变成这样了，似乎滑动之后才是正确的size，我自己写的demo也是这种情况，找了很久也没找到解决办法。

[图二](http://7teblm.com1.z0.glb.clouddn.com/QQ20150415-2@2x.png)
![](http://7teblm.com1.z0.glb.clouddn.com/QQ20150415-2@2x.png)

**Comment by xhzengAIB** [comment]
应该是我的约束没有写好！
